version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region us-west-1 | docker login --username AWS --password-stdin 938527394547.dkr.ecr.us-west-1.amazonaws.com
  build:
    commands:
      - docker build -t youtube:latest .
      - docker tag youtube:latest 938527394547.dkr.ecr.us-west-1.amazonaws.com/youtube:latest
  post_build:
    commands:
      - docker push 938527394547.dkr.ecr.us-west-1.amazonaws.com/youtube:latest
      - printf '[{"name":"helloWorld","imageUri":"%s"}]' 938527394547.dkr.ecr.us-west-1.amazonaws.com/youtube:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
